language: scala

jdk:
  - openjdk8

scala:
  - 2.11.12

env:
  matrix:
    - PROFILE=test
    - PROFILE=check

install: echo "skip preparatory install"

script:
  - if [ "$PROFILE" = "test" ]; then mvn -e -q clean test; fi
  - if [ "$PROFILE" = "check" ]; then mvn -e -q clean install -Dcluster -DskipTests; fi
